export const DEFAULT_SNIPPET_LANGUAGE = 'text';

export const SUPPORTED_LANGUAGES = [
    'text',
    'javascript',
    'typescript',
    'python',
    'java',
    'csharp',
    'html',
    'css',
    'php',
    'ruby',
    'swift',
    'kotlin',
    'bash',
    'json',
    'yaml',
    'markdown',
    'xml',
    'sql',
    'go',
    'rust',
    'perl',
    'r',
    'lua',
    'powershell',
    'dockerfile',
    'ini',
    'c',
    'cpp',
    'objective-c',
    'shellscript',
];

export const LANGUAGE_LABELS = {
    text: 'Plain Text',
    javascript: 'JavaScript',
    typescript: 'TypeScript',
    python: 'Python',
    java: 'Java',
    csharp: 'C#',
    html: 'HTML',
    css: 'CSS',
    php: 'PHP',
    ruby: 'Ruby',
    swift: 'Swift',
    kotlin: 'Kotlin',
    bash: 'Bash',
    json: 'JSON',
    yaml: 'YAML',
    markdown: 'Markdown',
    xml: 'XML',
    sql: 'SQL',
    go: 'Go',
    rust: 'Rust',
    perl: 'Perl',
    r: 'R',
    lua: 'Lua',
    powershell: 'PowerShell',
    dockerfile: 'Dockerfile',
    ini: 'INI',
    c: 'C',
    cpp: 'C++',
    'objective-c': 'Objective-C',
    shellscript: 'Shell Script',
};

export const LANGUAGE_EXTENSIONS = {
    javascript: '.js',
    typescript: '.ts',
    python: '.py',
    java: '.java',
    csharp: '.cs',
    html: '.html',
    css: '.css',
    php: '.php',
    ruby: '.rb',
    swift: '.swift',
    kotlin: '.kt',
    bash: '.sh',
    json: '.json',
    yaml: '.yaml',
    markdown: '.md',
    xml: '.xml',
    sql: '.sql',
    go: '.go',
    rust: '.rs',
    perl: '.pl',
    r: '.r',
    lua: '.lua',
    powershell: '.ps1',
    dockerfile: 'Dockerfile',
    ini: '.ini',
    c: '.c',
    cpp: '.cpp',
    'objective-c': '.m',
    shellscript: '.sh',
};